/*
 * @Date           : 2020-10-22 21:48:40
 * @FilePath       : /jinnian-space/src/pages/bookshelf/config/book_to_buy.js
 * @Description    : 
 */
 
 export default[
    { type:'科普',lang:'zh',name:"中国国家地理百科全书",taozhuang : true, num:10,buy:0}, 
    { type:'科普',lang:'zh',name:"环球国家地理百科全书",taozhuang : true, num:10,buy:0}, 
    { type:'小说',lang:'en',name:"哈利波特(1-7)",taozhuang : true, num:7,buy:0}, 
    { type:'科普',lang:'zh',name:"BBC科普--地球-行星的力量",taozhuang : true, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"BBC科普--海洋-深水探秘",taozhuang : true, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"BBC科普--生命-非常的世界",taozhuang : true, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"BBC宇宙科普--宇宙起源",taozhuang : true, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"BBC宇宙科普--宇宙之光",taozhuang : true, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"BBC宇宙科普--宇宙星辰",taozhuang : true, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"BBC--4K海洋百科 蓝色星球二",taozhuang : false, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"BBC--飞跃地球",taozhuang : false, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"BBC--地球脉动",taozhuang : false, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"BBC--地球脉动2 -奇迹世界",taozhuang : false, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"BBC--冰冻星球",taozhuang : false, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"BBC--生命的故事",taozhuang : false, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"BBC--俯瞰地球",taozhuang : false, num:1,buy:0},
    { type:'科普',lang:'zh',name:"天文摄影指南",taozhuang : false, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"DK博物大百科",taozhuang : false, num:1,buy:0}, 
    { type:'经典科普',lang:'zh',name:"世界科普10本-几何原本",taozhuang : false, num:1,buy:0}, 
    { type:'经典科普',lang:'zh',name:"世界科普10本-物种起源",taozhuang : false, num:1,buy:0}, 
    { type:'经典科普',lang:'zh',name:"世界科普10本-自然史",taozhuang : false, num:1,buy:0}, 
    { type:'经典科普',lang:'zh',name:"世界科普10本-相对论",taozhuang : false, num:1,buy:0}, 
    { type:'经典科普',lang:'zh',name:"世界科普10本-基因论",taozhuang : false, num:1,buy:0}, 
    { type:'经典科普',lang:'zh',name:"世界科普10本-人在自然界的位置",taozhuang : false, num:1,buy:0}, 
    { type:'经典科普',lang:'zh',name:"世界科普10本-天体运行论",taozhuang : false, num:1,buy:0}, 
    { type:'经典科普',lang:'zh',name:"世界科普10本-自然哲学之数学原理",taozhuang : false, num:1,buy:0}, 
    { type:'经典科普',lang:'zh',name:"世界科普10本-通俗天文学",taozhuang : false, num:1,buy:0}, 
    { type:'经典科普',lang:'zh',name:"世界科普10本-海陆的起源",taozhuang : false, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"地球与太空--太空传奇",taozhuang : false, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"地球与太空--行星全书",taozhuang : false, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"地球与太空--星座全书",taozhuang : false, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"地球与太空--从粒子到宇宙",taozhuang : false, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"地球与太空--地球与太空",taozhuang : false, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"太空--纸上天文馆",taozhuang : false, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"简史--今日简史",taozhuang : false, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"简史--万物简史",taozhuang : false, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"简史--时间简史",taozhuang : false, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"简史--未来简史",taozhuang : false, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"简史--人类简史",taozhuang : false, num:1,buy:0}, 
    { type:'科普',lang:'zh',name:"简史--宇宙简史",taozhuang : false, num:1,buy:0}, 
    { type:'人生原则',lang:'zh',name:"原则--原则",taozhuang : false, num:1,buy:0}, 
    { type:'人生原则',lang:'zh',name:"原则--阿里巴巴人力资源管理",taozhuang : false, num:1,buy:0}, 
    { type:'人生原则',lang:'zh',name:"原则--阿米巴经管理",taozhuang : false, num:1,buy:0}, 
    { type:'人生原则',lang:'zh',name:"原则--华为人力资源管理",taozhuang : false, num:1,buy:0}, 
    { type:'人生原则',lang:'zh',name:"原则--稻盛和夫给年轻人的忠告",taozhuang : false, num:1,buy:0}, 
    { type:'人生原则',lang:'zh',name:"原则--格局",taozhuang : false, num:1,buy:0}, 
    { type:'人生原则',lang:'zh',name:"原则--见识",taozhuang : false, num:1,buy:0}, 
    { type:'人生原则',lang:'zh',name:"原则--情商",taozhuang : false, num:1,buy:0}, 
    { type:'人生原则',lang:'zh',name:"原则--眼界",taozhuang : false, num:1,buy:0}, 
    { type:'人生原则',lang:'zh',name:"原则--策略",taozhuang : false, num:1,buy:0}, 
    { type:'思维训练',lang:'zh',name:"思维训练--思维导图",taozhuang : false, num:1,buy:0}, 
    { type:'思维训练',lang:'zh',name:"思维训练--思维风暴",taozhuang : false, num:1,buy:0}, 
    { type:'思维训练',lang:'zh',name:"思维训练--最强大脑",taozhuang : false, num:1,buy:0}, 
    { type:'思维训练',lang:'zh',name:"思维训练--高效记忆法",taozhuang : false, num:1,buy:0}, 
    { type:'思维训练',lang:'zh',name:"思维训练--超级记忆术",taozhuang : false, num:1,buy:0}, 
    { type:'思维训练',lang:'zh',name:"思维训练--锻炼思维的逻辑游戏",taozhuang : false, num:1,buy:0}, 
    { type:'思维训练',lang:'zh',name:"思维训练--逆转思维",taozhuang : false, num:1,buy:0}, 
    { type:'思维训练',lang:'zh',name:"思维训练--认知天性",taozhuang : false, num:1,buy:0}, 
    { type:'思维训练',lang:'zh',name:"思维训练--挑战大脑的侦探推理游戏",taozhuang : false, num:1,buy:0}, 
    { type:'思维训练',lang:'zh',name:"思维训练--超级学习力",taozhuang : false, num:1,buy:0}, 
    { type:'思维训练',lang:'zh',name:"思维训练--自控力",taozhuang : false, num:1,buy:0}, 
    { type:'戴尔卡耐基心理学',lang:'zh',name:"戴尔卡耐基--人性的弱点",taozhuang : true, num:1,buy:0}, 
    { type:'戴尔卡耐基心理学',lang:'zh',name:"戴尔卡耐基--人性的突破",taozhuang : true, num:1,buy:0}, 
    { type:'戴尔卡耐基心理学',lang:'zh',name:"戴尔卡耐基--卡耐基传",taozhuang : true, num:1,buy:0}, 
    { type:'戴尔卡耐基心理学',lang:'zh',name:"戴尔卡耐基--语言的艺术",taozhuang : true, num:1,buy:0}, 
    { type:'戴尔卡耐基心理学',lang:'zh',name:"戴尔卡耐基--人生箴言",taozhuang : true, num:1,buy:0}, 
    { type:'戴尔卡耐基心理学',lang:'zh',name:"戴尔卡耐基--林肯外传",taozhuang : true, num:1,buy:0}, 
    { type:'创业心理学',lang:'zh',name:"创业心理学--低风险创业",taozhuang : false, num:1,buy:0}, 
    { type:'创业心理学',lang:'zh',name:"创业心理学--塔木德",taozhuang : false, num:1,buy:0}, 
    { type:'创业心理学',lang:'zh',name:"创业心理学--羊皮卷",taozhuang : false, num:1,buy:0}, 
    { type:'创业心理学',lang:'zh',name:"创业心理学--领导力法则",taozhuang : false, num:1,buy:0}, 
    { type:'创业心理学',lang:'zh',name:"创业心理学--狼道",taozhuang : false, num:1,buy:0}, 
    { type:'创业心理学',lang:'zh',name:"创业心理学--玩的就是心计",taozhuang : false, num:1,buy:0}, 
    { type:'创业心理学',lang:'zh',name:"创业心理学--微表情心理学",taozhuang : false, num:1,buy:0}, 
    { type:'创业心理学',lang:'zh',name:"创业心理学--沃顿谈判课",taozhuang : false, num:1,buy:0}, 
    { type:'创业心理学',lang:'zh',name:"创业心理学--沃尔森法则",taozhuang : false, num:1,buy:0}, 
    { type:'创业心理学',lang:'zh',name:"创业心理学--吉德林法则",taozhuang : false, num:1,buy:0}, 
    { type:'华为企业管理',lang:'zh',name:"华为任正非--华为方法",taozhuang : true, num:1,buy:0},
    { type:'华为企业管理',lang:'zh',name:"华为任正非--华为创新管理",taozhuang : true, num:1,buy:0},
    { type:'华为企业管理',lang:'zh',name:"华为任正非--华为管理哲学",taozhuang : true, num:1,buy:0},
    { type:'华为企业管理',lang:'zh',name:"华为任正非--华为离职江湖",taozhuang : true, num:1,buy:0},
    { type:'华为企业管理',lang:'zh',name:"华为任正非--神坛在坐华为往右",taozhuang : true, num:1,buy:0},
    { type:'华为企业管理',lang:'zh',name:"华为任正非--华为的冬天",taozhuang : true, num:1,buy:0},
    { type:'华为企业管理',lang:'zh',name:"华为任正非--以奋斗着为本",taozhuang : true, num:1,buy:0},
    { type:'华为企业管理',lang:'zh',name:"华为任正非--以客户为中心",taozhuang : true, num:1,buy:0},
    { type:'华为企业管理',lang:'zh',name:"华为任正非--天道酬勤",taozhuang : true, num:1,buy:0},
    { type:'华为企业管理',lang:'zh',name:"华为任正非--致新员工书",taozhuang : true, num:1,buy:0},
    { type:'华为企业管理',lang:'zh',name:"华为任正非--华为之秘",taozhuang : true, num:1,buy:0},
    { type:'华为企业管理',lang:'zh',name:"华为任正非--任正非",taozhuang : true, num:1,buy:0},
    { type:'华为企业管理',lang:'zh',name:"华为任正非--世界极客任正非",taozhuang : true, num:1,buy:0},
     

    { type:'管理',lang:'zh',name:"管理--不懂带团队，你就自己累",taozhuang : false, num:1,buy:0}, 
    { type:'管理',lang:'zh',name:"管理--管理三要：能识人会用人懂管理",taozhuang : false, num:1,buy:0}, 
    { type:'管理',lang:'zh',name:"管理--领导力法则",taozhuang : false, num:1,buy:0}, 
    { type:'管理',lang:'zh',name:"管理--如何说，员工才会听",taozhuang : false, num:1,buy:0}, 
    { type:'管理',lang:'zh',name:"管理--高情商管理，三分管人，七分做人",taozhuang : false, num:1,buy:0}, 
    { type:'经济学',lang:'zh',name:"经济学--博弈论",taozhuang : false, num:1,buy:0}, 
    { type:'经济学',lang:'zh',name:"经济学--经济常识一本全",taozhuang : false, num:1,buy:0}, 
    { type:'经济学',lang:'zh',name:"经济学--经济学（越简单越实用）",taozhuang : false, num:1,buy:0}, 
    { type:'经济学',lang:'zh',name:"经济学--你的第一本金融学",taozhuang : false, num:1,buy:0}, 
    { type:'经济学',lang:'zh',name:"经济学--北大经济课",taozhuang : false, num:1,buy:0}, 
    { type:'经济学',lang:'zh',name:"经济学--国富论",taozhuang : false, num:1,buy:0}, 
    { type:'投资管理',lang:'zh',name:"生活和工作原则--瑞达利著",taozhuang : false, num:1,buy:0}, 
    { type:'投资管理',lang:'zh',name:"债务危机--瑞达利著",taozhuang : false, num:1,buy:0}, 
    { type:'北大金书',lang:'zh',name:"人生金书系列--北大经济课",taozhuang : true, num:1,buy:0}, 
    { type:'北大金书',lang:'zh',name:"人生金书系列--北大人文课",taozhuang : true, num:1,buy:0}, 
    { type:'北大金书',lang:'zh',name:"人生金书系列--北大投资课",taozhuang : true, num:1,buy:0}, 
    { type:'北大金书',lang:'zh',name:"人生金书系列--北大金融课",taozhuang : true, num:1,buy:0}, 
    { type:'北大金书',lang:'zh',name:"人生金书系列--经济学一本通",taozhuang : true, num:1,buy:0}, 
    { type:'北大金书',lang:'zh',name:"人生金书系列--北大口才课",taozhuang : true, num:1,buy:0}, 
    { type:'北大金书',lang:'zh',name:"人生金书系列--北大国学课",taozhuang : true, num:1,buy:0}, 
    { type:'北大金书',lang:'zh',name:"人生金书系列--北大心理课",taozhuang : true, num:1,buy:0}, 
    { type:'北大金书',lang:'zh',name:"人生金书系列--北大管理课",taozhuang : true, num:1,buy:0}, 
    { type:'北大金书',lang:'zh',name:"人生金书系列--北大哲学课",taozhuang : true, num:1,buy:0}, 


    { type:'哈弗管理',lang:'zh',name:"哈弗管理全集--管理者手册",taozhuang : true, num:1,buy:0},
    { type:'哈弗管理',lang:'zh',name:"哈弗管理全集--企业培训管理",taozhuang : true, num:1,buy:0},
    { type:'哈弗管理',lang:'zh',name:"哈弗管理全集--生产与品质管理",taozhuang : true, num:1,buy:0},
    { type:'哈弗管理',lang:'zh',name:"哈弗管理全集--办公行政管理",taozhuang : true, num:1,buy:0},
    { type:'哈弗管理',lang:'zh',name:"哈弗管理全集--市场营销管理",taozhuang : true, num:1,buy:0},
    { type:'哈弗管理',lang:'zh',name:"哈弗管理全集--人力资源管理",taozhuang : true, num:1,buy:0},
    { type:'哈弗管理',lang:'zh',name:"哈弗管理全集--财务管理",taozhuang : true, num:1,buy:0},
    { type:'哈弗管理',lang:'zh',name:"哈弗管理全集--投资管理",taozhuang : true, num:1,buy:0},

    { type:'财经',lang:'zh',name:"财经人物传记--巴菲特",taozhuang : false, num:1,buy:0}, 
    { type:'财经',lang:'zh',name:"财经人物传记--李嘉诚",taozhuang : false, num:1,buy:0}, 
    { type:'财经',lang:'zh',name:"财经人物传记--乔布斯",taozhuang : false, num:1,buy:0}, 
    { type:'财经',lang:'zh',name:"财经人物传记--德鲁克说管理",taozhuang : false, num:1,buy:0}, 
    { type:'财经',lang:'zh',name:"财经人物传记--科特勒营销全书",taozhuang : false, num:1,buy:0}, 
    { type:'商界',lang:'zh',name:"商界40年--弄潮儿",taozhuang : true, num:1,buy:0}, 
    { type:'商界',lang:'zh',name:"商界40年--先行者",taozhuang : true, num:1,buy:0}, 
    { type:'商界',lang:'zh',name:"商界40年--梦想家",taozhuang : true, num:1,buy:0}, 
    { type:'商界',lang:'zh',name:"商界40年--逐鹿人",taozhuang : true, num:1,buy:0}, 
    { type:'营销-淘宝',lang:'zh',name:"营销淘宝--淘宝天猫开店一本通",taozhuang : false, num:1,buy:0}, 
    { type:'营销-淘宝',lang:'zh',name:"营销淘宝--淘宝天猫SEO",taozhuang : false, num:1,buy:0}, 
    { type:'营销-淘宝',lang:'zh',name:"营销淘宝--社群营销",taozhuang : false, num:1,buy:0}, 
    { type:'营销-淘宝',lang:'zh',name:"营销淘宝--从零开始学运营",taozhuang : false, num:1,buy:0}, 
    { type:'营销-淘宝',lang:'zh',name:"营销淘宝--营销策划食用技巧",taozhuang : false, num:1,buy:0}, 
    { type:'营销-淘宝',lang:'zh',name:"营销淘宝--别输在不懂营销上",taozhuang : false, num:1,buy:0}, 
    { type:'处世智慧',lang:'zh',name:"处世智慧--鬼谷子",taozhuang : false, num:1,buy:0}, 
    { type:'处世智慧',lang:'zh',name:"处世智慧--羊皮卷",taozhuang : false, num:1,buy:0}, 
    { type:'处世智慧',lang:'zh',name:"处世智慧--墨菲定律",taozhuang : false, num:1,buy:0}, 
    { type:'处世智慧',lang:'zh',name:"处世智慧--人性的弱点",taozhuang : false, num:1,buy:0}, 
    { type:'处世智慧',lang:'zh',name:"处世智慧--狼道",taozhuang : false, num:1,buy:0}, 
    { type:'处世智慧',lang:'zh',name:"处世智慧--口才三绝",taozhuang : false, num:1,buy:0}, 
    { type:'处世智慧',lang:'zh',name:"处世智慧--为人三会",taozhuang : false, num:1,buy:0}, 
    { type:'处世智慧',lang:'zh',name:"处世智慧--修心三不",taozhuang : false, num:1,buy:0}, 
    { type:'处世智慧',lang:'zh',name:"处世智慧--格局",taozhuang : false, num:1,buy:0}, 
    { type:'处世智慧',lang:'zh',name:"处世智慧--高情商办事就让人舒服",taozhuang : false, num:1,buy:0}, 
    { type:'处世智慧',lang:'zh',name:"处世智慧--人际关系心理学",taozhuang : false, num:1,buy:0}, 
    { type:'处世智慧',lang:'zh',name:"处世智慧--跟任何人都能聊得来",taozhuang : false, num:1,buy:0}, 
    { type:'计算机',lang:'zh',name:"计算机--计算机程序设计艺术-基本算法",taozhuang : true, num:1,buy:0}, 
    { type:'计算机',lang:'zh',name:"计算机--计算机程序设计艺术-半数值算法",taozhuang : true, num:1,buy:0}, 
    { type:'计算机',lang:'zh',name:"计算机--计算机程序设计艺术-排序与查找",taozhuang : true, num:1,buy:0}, 
    { type:'计算机',lang:'zh',name:"计算机--计算机程序设计艺术-组合算法",taozhuang : true, num:1,buy:0}, 

    { type:'计算机',lang:'zh',name:"计算机--计算机科学技术百科全书",taozhuang : false, num:1,buy:0}, 
    { type:'计算机',lang:'zh',name:"计算机--其他语言书籍",taozhuang : false, num:1000,buy:0}, 

    

]

